### ISSUE TITLE
Library issue with ambpdb

### ISSUE THREAD

**Issue by dww100** [conda-forge/ambertools-feedstock#13] opened 2019-11-08 17:41 UTC
Issue:
Not sure if this is the right place for this, but, when I run `ambpdb` from the conda build of AmberTools I get the following error:

```
ambpdb: error while loading shared libraries: /home/conda/feedstock_root/build_artifacts/ambertools_1571761492881/work/lib/libcpptraj.so: cannot open shared object file: No such file or directory
```

<br/>
Environment (<code>conda list</code>):
<details>

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
amberlite                 16.0                     pypi_0    pypi
ambertools                17.0                     pypi_0    pypi
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0                hc9558a2_2    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
matplotlib                3.1.2                    py37_0    conda-forge
matplotlib-base           3.1.2            py37h250f245_0    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
nspr                      4.23                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packmol-memgen            1.0.5rc0                 pypi_0    pypi
parmed                    3.2.0                    pypi_0    pypi
pcre                      8.43                 he1b5a44_0    conda-forge
pdb4amber                 1.7.dev0                 pypi_0    pypi
pip                       19.3.1                   py37_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.4                      py_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_0    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytraj                    2.0.5                    pypi_0    pypi
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.3.1            py37h921218d_2    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
six                       1.13.0                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

     active environment : test
    active env location : /home/dave/anaconda3/envs/test
            shell level : 3
       user config file : /home/dave/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /home/dave/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dave/anaconda3/pkgs
                          /home/dave/.conda/pkgs
       envs directories : /home/dave/anaconda3/envs
                          /home/dave/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-66-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

</details>

**Comment by simonbray** [comment] 2019-11-11 15:20
I can reproduce this with the conda package installed from the `ambermd` channel as well, so it doesn't seem to be an issue unique to the conda-forge build.

Thanks for reporting this!

ping @dacase

**Comment by dacase** [comment] 2019-11-11 16:08
I'll post a note to the Amber reflector about this -- it doesn't look like Hai Nguyen is watching this github issue.

**Comment by dacase** [comment] 2019-11-11 16:16
@dww100 -- can you be more specific about what you mean by "the conda build of AmberTools"?
The error message refers to "feedstock_root", which makes me think you are trying a conda package made from this (ambertools-feedstock) repository, but I'd like to be sure.

There is also an "official" Ambertools package which one gets via 'conda install ambertools=19 -c ambermd`, and I don't know if the error you see here would be found with that package as well.

...thx...dac

**Comment by hainm** [comment] 2019-11-11 16:23
@dacase  the error happens in both channels (ambermd and conda-forge) (that I don't have time yet to fix). Please not that this would happen even if user build AT from source and move the folder tree to different path. cc @drroe

**Comment by drroe** [comment] 2019-11-11 17:23
Pretty sure the changes to the main Amber GIT repo (specifically [Compile ambpdb with static cpptraj libraries](https://gitlab.ambermd.org/amber/amber/merge_requests/261)) will fix this.

**Comment by jaimergp** [comment] 2020-01-24 00:44
This might have been fixed in the last builds after switching to `cmake`, since `conda build` will patch hardcoded `$PREFIX` occurrences. Can you check, @dww100?

**Comment by dww100** [comment] 2020-01-24 11:31
Running: `conda install -c conda-forge ambertools` in a fresh environment provides a version of AmberTools without `ambpdb` for me.

**Comment by jaimergp** [comment] 2020-01-24 11:45
Hm, you are right! It seems like `ambpdb` is not included in the CMake build system. Is this intentional, @multiplemonomials?

**Comment by jaimergp** [comment] 2020-04-13 19:13
New AT20 does include `ambpdb`! We are testing the release candidates now and you can see how the CLI tests (which include `ambpdb -h`) do pass.

**Closed** 2020-05-05 10:13 UTC
